### ISSUE TITLE
java2smali on IntelliJ IDEA Community Edition 14.1.5 NullPointerException: null

### ISSUE THREAD

**Issue by wasssup** [ollide/intellij-java2smali#2]
null
java.lang.NullPointerException
	at org.ollide.java2smali.GenerateAction$CompilerCallback.finished(GenerateAction.java:81)
	at com.intellij.compiler.CompilerManagerImpl$ListenerNotificator.finished(CompilerManagerImpl.java:325)
	at com.intellij.compiler.impl.CompileDriver$5.run(CompileDriver.java:509)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ollide** [comment]
I've installed 14.1.5 CE and created a simple Java module with one source file and it turned out that the file compiled into smali just fine.

Please make sure that your module has an output path specified (-> Configure Project) because the plugin triggers the compiler and then accesses the output directory to transfer the .class file into smali.

Eventually I will try to detect this situation and give some meaningful advice rather than throwing an exception.
