### ISSUE TITLE
code fails to compile

### ISSUE THREAD

**Issue by botgod** [ollide/intellij-java2smali#5]
Error:Internal error: (java.util.concurrent.ExecutionException) java.lang.NoClassDefFoundError: org/jetbrains/jps/android/model/impl/JpsAndroidModuleProperties
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/jetbrains/jps/android/model/impl/JpsAndroidModuleProperties
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.jetbrains.jps.model.serialization.JpsProjectLoader.loadModules(JpsProjectLoader.java:281)
	at org.jetbrains.jps.model.serialization.JpsProjectLoader.loadModules(JpsProjectLoader.java:238)
	at org.jetbrains.jps.model.serialization.JpsProjectLoader.loadFromDirectory(JpsProjectLoader.java:124)
	at org.jetbrains.jps.model.serialization.JpsProjectLoader.loadProject(JpsProjectLoader.java:100)
	at org.jetbrains.jps.model.serialization.impl.JpsSerializationManagerImpl.loadModel(JpsSerializationManagerImpl.java:41)
	at org.jetbrains.jps.cmdline.JpsModelLoaderImpl.loadModel(JpsModelLoaderImpl.java:45)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:78)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:266)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/jps/android/model/impl/JpsAndroidModuleProperties
	at org.jetbrains.jps.android.model.impl.JpsAndroidModelSerializerExtension$1.loadExtension(JpsAndroidModelSerializerExtension.java:52)
	at org.jetbrains.jps.android.model.impl.JpsAndroidModelSerializerExtension$1.loadExtension(JpsAndroidModelSerializerExtension.java:47)
	at org.jetbrains.jps.model.serialization.facet.JpsFacetConfigurationSerializer.loadExtension(JpsFacetConfigurationSerializer.java:46)
	at org.jetbrains.jps.model.serialization.facet.JpsFacetSerializer.addExtension(JpsFacetSerializer.java:73)
	at org.jetbrains.jps.model.serialization.facet.JpsFacetSerializer.addFacets(JpsFacetSerializer.java:65)
	at org.jetbrains.jps.model.serialization.facet.JpsFacetSerializer.loadFacets(JpsFacetSerializer.java:45)
	at org.jetbrains.jps.model.serialization.JpsProjectLoader.loadModule(JpsProjectLoader.java:323)
	at org.jetbrains.jps.model.serialization.JpsProjectLoader.access$000(JpsProjectLoader.java:62)
	at org.jetbrains.jps.model.serialization.JpsProjectLoader$2.call(JpsProjectLoader.java:276)
	at org.jetbrains.jps.model.serialization.JpsProjectLoader$2.call(JpsProjectLoader.java:273)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.jetbrains.jps.android.model.impl.JpsAndroidModuleProperties
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

**Comment by ollide** [comment]
Hi @botgod,
did your module only fail to compile when you try to convert a class to smali or is there a problem with your module in general? If it only fails when compiling to smali, please try again with the newly released version 1.5.

If you still encounter problems, please provide more information (project sdk, IntilliJ platform, platform runtime, etc.).
